(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/news-detail/news-detail"],{"3a1a":
/*!***********************************************************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/temp111/front/pages/news-detail/news-detail.vue?vue&type=style&index=0&id=3b1ac260&scoped=true&lang=css& ***!
  \***********************************************************************************************************************************************/
/*! no static exports found */
/*! ModuleConcatenation bailout: Module exports are unknown */function(n,t,e){"use strict";var r=e(/*! -!./node_modules/_mini-css-extract-plugin@0.9.0@mini-css-extract-plugin/dist/loader.js??ref--6-oneOf-1-0!./node_modules/_css-loader@3.6.0@css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--6-oneOf-1-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--6-oneOf-1-3!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!./news-detail.vue?vue&type=style&index=0&id=3b1ac260&scoped=true&lang=css& */"921d"),a=e.n(r);a.a},4842:
/*!*********************************************************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/temp111/front/pages/news-detail/news-detail.vue?vue&type=template&id=3b1ac260&scoped=true& + 1 modules ***!
  \*********************************************************************************************************************************************/
/*! exports provided: render, staticRenderFns, recyclableRender, components */
/*! exports used: components, render, staticRenderFns */function(n,t,e){"use strict";var r;e.d(t,"b",(function(){return a})),e.d(t,"c",(function(){return u})),e.d(t,"a",(function(){return r}));var a=function(){var n=this,t=n.$createElement;n._self._c},u=[]},"6b28":
/*!***************************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/temp111/front/pages/news-detail/news-detail.vue?vue&type=script&lang=js& ***!
  \***************************************************************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module exports are unknown */function(n,t,e){"use strict";e.r(t);var r=e(/*! -!./node_modules/_babel-loader@8.2.3@babel-loader/lib!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!./news-detail.vue?vue&type=script&lang=js& */"cdf6"),a=e.n(r);for(var u in r)["default"].indexOf(u)<0&&function(n){e.d(t,n,(function(){return r[n]}))}(u);t["default"]=a.a},"921d":
/*!*****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/_mini-css-extract-plugin@0.9.0@mini-css-extract-plugin/dist/loader.js??ref--6-oneOf-1-0!./node_modules/_css-loader@3.6.0@css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--6-oneOf-1-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--6-oneOf-1-3!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!C:/Users/Administrator/Desktop/temp111/front/pages/news-detail/news-detail.vue?vue&type=style&index=0&id=3b1ac260&scoped=true&lang=css& ***!
  \*****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
/*! no static exports found */
/*! exports used: default */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(n,t,e){},bb88:
/*!*********************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/temp111/front/main.js?{"page":"pages%2Fnews-detail%2Fnews-detail"} ***!
  \*********************************************************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(n,t,e){"use strict";(function(n){e(/*! uni-pages */"f988");r(e(/*! vue */"8fa0"));var t=r(e(/*! ./pages/news-detail/news-detail.vue */"c251"));function r(n){return n&&n.__esModule?n:{default:n}}wx.__webpack_require_UNI_MP_PLUGIN__=e,n(t.default)}).call(this,e(/*! ./node_modules/_@dcloudio_uni-mp-weixin@2.0.1-alpha-34020211231004@@dcloudio/uni-mp-weixin/dist/index.js */"9b21")["createPage"])},c251:
/*!**************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/temp111/front/pages/news-detail/news-detail.vue ***!
  \**************************************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module exports are unknown */function(n,t,e){"use strict";e.r(t);var r=e(/*! ./news-detail.vue?vue&type=template&id=3b1ac260&scoped=true& */"4842"),a=e(/*! ./news-detail.vue?vue&type=script&lang=js& */"6b28");for(var u in a)["default"].indexOf(u)<0&&function(n){e.d(t,n,(function(){return a[n]}))}(u);e(/*! ./news-detail.vue?vue&type=style&index=0&id=3b1ac260&scoped=true&lang=css& */"3a1a");var i,c=e(/*! ./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/runtime/componentNormalizer.js */"5140"),o=Object(c["a"])(a["default"],r["b"],r["c"],!1,null,"3b1ac260",null,!1,r["a"],i);t["default"]=o.exports},cdf6:
/*!************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/_babel-loader@8.2.3@babel-loader/lib!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!C:/Users/Administrator/Desktop/temp111/front/pages/news-detail/news-detail.vue?vue&type=script&lang=js& ***!
  \************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(n,t,e){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var r=a(e(/*! ./node_modules/_@babel_runtime@7.16.7@@babel/runtime/regenerator/index.js */"7da1"));function a(n){return n&&n.__esModule?n:{default:n}}function u(n,t,e,r,a,u,i){try{var c=n[u](i),o=c.value}catch(f){return void e(f)}c.done?t(o):Promise.resolve(o).then(r,a)}function i(n){return function(){var t=this,e=arguments;return new Promise((function(r,a){var i=n.apply(t,e);function c(n){u(i,r,a,c,o,"next",n)}function o(n){u(i,r,a,c,o,"throw",n)}c(void 0)}))}}var c={data:function(){return{detail:{},id:""}},onLoad:function(n){var t=this;return i(r.default.mark((function e(){var a;return r.default.wrap((function(e){while(1)switch(e.prev=e.next){case 0:return t.id=n.id,e.next=3,t.$api.info("news",n.id);case 3:a=e.sent,t.detail=a.data,t.detail.content=t.detail.content.replace(/<img/g,'<img style="width: 100%;"');case 6:case"end":return e.stop()}}),e)})))()}};t.default=c}},[["bb88","common/runtime","common/vendor"]]]);